---
title: "Problem 2"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---


```{r setup, include=FALSE}
library(flexdashboard)

library(tidyverse)
library(plotly)
library(p8105.datasets)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
data("rest_inspec")                                                                          # load data

rest_inspec_df =                                                             # filter interested dataset
  rest_inspec |>
  filter(grade %in% c("A", "B", "C"), boro != "Missing") |> 
  mutate(boro = str_to_title(boro)) |>
  drop_na()

rest_inspec_df |>                                         # plot a figure shows the score from each boro
  plot_ly(y = ~score, color = ~boro, type = "box")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
# plot a figure shows the score from each boro in scatter plot

rest_inspec_df |>
  plot_ly(
  x = ~boro, y = ~score, color = ~score, type = "scatter", mode = "markers")
```

### Chart C


```{r}
# plot a figure shows the grade from each boro

rest_inspec_df |>
  group_by(boro, grade) |>
  summarize(n_obs = n()) |>
  plot_ly(x = ~boro, y = ~n_obs, color = ~grade, type = "bar")
```


